name: Build UF2 (Pico 2 W) CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    env:
      MPY_DIR: micropython
      PORT_DIR: micropython/ports/rp2
      VERSION: ${{ github.ref_name || github.sha }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Toolchain sanity
        run: |
          python3 --version || true
          arm-none-eabi-gcc --version || true
          cmake --version || true
          make --version || true

      - name: Clone MicroPython
        run: |
          git clone --depth 1 https://github.com/micropython/micropython.git "$MPY_DIR"
          cd "$MPY_DIR"
          git submodule update --init --recursive

      - name: Build mpy-cross
        run: make -C "$MPY_DIR/mpy-cross" -j"$(nproc)"

      - name: Create frozen manifest
        run: |
          cat > my_manifest.py << 'PY'
          include("$(PORT_DIR)/boards/manifest.py")
          freeze("$(GITHUB_WORKSPACE)", opt=3)
          module("pb_version.py", f"__version__ = '{'${{VERSION}}'}'\n")
          PY

      - name: Build UF2 (RPI_PICO2_W)
        working-directory: ${{ env.PORT_DIR }}
        run: |
          make submodules
          make clean
          make BOARD=RPI_PICO2_W FROZEN_MANIFEST=$GITHUB_WORKSPACE/my_manifest.py -j"$(nproc)"

      - name: Collect artifact
        run: |
          mkdir -p out
          cp "$PORT_DIR/build-RPI_PICO2_W/firmware.uf2" \
             "out/picobridge_${{ env.VERSION }}.uf2"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: picobridge-${{ env.VERSION }}
          path: out/picobridge_${{ env.VERSION }}.uf2
          if-no-files-found: error
